### ISSUE TITLE
[BUG] cannot launch uPMT.jar

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#40]
hi,

I am not able to launch the .jar, both on Windows and on Linux.

Here is the error I get on Windows 10:
uPMT>java -jar uPMT.jar
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at utils.Utils.loadProjects(Utils.java:72)
        at application.Main.initProjects(Main.java:211)
        at application.Main.start(Main.java:152)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
        ... 1 more
Exception running application application.Main

Java version is:
uPMT>java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

And here is the error and version on Linux:
$ java -jar uPMT.jar 
Error: Could not find or load main class application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode)

**Comment by yprie** [comment]
Hi. We are currently making a new version of uPMT, with a lot of modifications, so please wait for this new version. Best. Y.

**Comment by buscon** [comment]
thank you, looking forward to the new version of uPMT.

**Comment by Thykof** [comment]
Hi, you can download the new version here: <https://github.com/yprie/uPMT/releases/tag/v0.4.0>.
Then, unzip the downloaded file, and unzip `uPMT.zip`. Navigate into the `bin` folder and run `uPMT` (MacOS/Linux) or `uPMT.bat` (Windows).

**Comment by buscon** [comment]
Thanks a lot for answering, the software runs on Linux and it looks much better. In the next weeks/months we are using it for a research project, I will report back possible issues and feedback.

**Comment by yprie** [comment]
Hello. Glad to hear this. Could you please contact me on yannick.prie@univ-nantes.fr ? I am curious to learn about this research project, aims, participants, etc.
